development:
  clients:
    default:
      uri: mongodb+srv://hbnoboa:hbn110900@security-system.ecv1k.mongodb.net/db?retryWrites=true&w=majority&appName=security-system
      options:
        server_selection_timeout: 5
        timezone: "Brasilia"

production:
  clients:
    default:
      uri: mongodb+srv://hbnoboa:hbn110900@security-system.ecv1k.mongodb.net/db?retryWrites=true&w=majority&appName=security-system
      options:
        server_selection_timeout: 5
        timezone: "Brasilia"
